server:
  servlet:
    context-path: /api
  port: 8081

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    password: postgres
    username: postgres
  data:
    web:
      pageable:
        default-page-size: 20
